Repository whpptjs/whppt-nuxt, pull requests merged in 2020-11, with the labels that each got.

#10 w-content whitelisting and blacklisting
  lib/components/content/Content.vue
  lib/components/editors/Content.vue
  lib/plugins/directives/content.js
Labels: enhancement

#11 Fixed before/after(Un)publish default variables
  lib/plugins/pluginDefaults.js
Labels: awaiting release, bug

#13 getImage supports transparent option
  lib/plugins/helpers/Image.js
Labels: enhancement

#12 pass container through to content to indicate root level component, s…
  lib/components/content/Content.vue
Labels: enhancement

#15 removed page binding on mounted
  lib/components/system/WhpptPage.vue
Labels: bug

#17 Bring in context for before/after(Un)publish
  lib/plugins/pluginDefaults.js
Labels: enhancement

#19 Directives to be disabled via v-whppt-enabled
  lib/plugins/directives/dynamic.js
  lib/plugins/directives/editorEnabled.js
  lib/plugins/directives/image.js
  lib/plugins/directives/index.js
  lib/plugins/directives/link.js
  lib/plugins/directives/list.js
  lib/plugins/index.js
Labels: enhancement

#22 Allow for a custom class on content components
  lib/components/content/Content.vue
  lib/plugins/directives/editorEnabled.js
  lib/plugins/directives/link.js
Labels: awaiting release, enhancement
